# Generated by Django 4.1.3 on 2022-11-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_youranswer_course_studentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
    ]
