# Generated by Django 4.1.3 on 2022-11-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_studentcourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.addcourse'),
            preserve_default=False,
        ),
    ]
