# Generated by Django 4.1.3 on 2022-11-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_studentcourse_user_alter_submitexam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.addcourse'),
        ),
    ]
