# Generated by Django 4.1.3 on 2022-11-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_studentcourse_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addquestion',
            old_name='answer',
            new_name='option',
        ),
    ]
